### ISSUE TITLE
Run CI over feature profiles

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#267]
As the test suite and ref impl support feature flags, we need a way to specify a set of feature profiles against which we can test the reference implementation

Simple suggested approach:

- Each feature profile is given a name, e.g. "single-seller".
- A config file is created within the test suite named `example-single-seller.json`, which can be set in CI via `NODE_ENV = example-${{ matrix.profile }}`
- The reference app is updated with a mapping from the string "single-seller" to an array of feature flags, within the .NET code, which is based on an environment variable e.g. `FeatureProfile`

A CI script then uses the `matrix` to iterate through the profiles.

The matrix itself could hold the feature profiles using `include`: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations

```
strategy:
  matrix:
    profile: [single-seller, only-free, prepayment-unavailable, prepayment-optional, anon-lease, named-lease, no-lease]
    include:
      - profile: single-seller
        flags: SingleSeller
        npm: 2
```

However it's likely the profile logic would sit better in the .NET app
