### ISSUE TITLE
Better documentation for how to run test suite with docker, and also with GitHub Actions

### ISSUE THREAD

**Issue by lukehesluke** [openactive/openactive-test-suite#682]
Explain all of the following:

```
docker run -it -e INPUT_CONFIG=/config/strmln.json -e NODE_ENV=strmln -p 3000:3000 -v ${PWD}/config:/config -v ${PWD}/packages/openactive-integration-tests/output:/openactive-test-suite/packages/openactive-integration-tests/output ghcr.io/openactive/test-suite:latest -- booking-partner-authentication
```

And potentially simplify this command too

Also explain the following:

Assuming dev.json is renamed openactive-test-suite-config.json and exists in a directory named example-booking-system in the GitHub workspace, and assuming that within the GitHub action the app is running on http://localhost:8081/ then the following should work currently, and output the resulting cert to conformance/ in the current workspace

```
    - name: Run OpenActive Test Suite
      uses: openactive/openactive-test-suite@d7cbdac7f03ce75f282927fe67c9a375f1e440a8
      with:
        config: example-booking-system/openactive-test-suite-config.json
        NODE_CONFIG: |
          { "ci": true, "consoleOutputLevel": "detail", "broker": {"datasetSiteUrl": "http://localhost:8081/openactive", "outputPath": "/github/workspace/output/"}, "integrationTests": {"testDatasetIdentifier": "github-ci", "outputPath": "/github/workspace/output/", "generateConformanceCertificate": true, "conformanceCertificatePath": "/github/workspace/conformance/", "conformanceCertificateId": "https://openactive-certificate.example.com/" }}
        NODE_ENV: openactive-test-suite-config

    - name: Upload OpenActive Test Suite output as artifact for debugging
      uses: actions/upload-artifact@v2
      if: ${{ success() || failure() }}
      with:
        name: openactive-test-suite
        path: ./output/

```

Ensure that all of the above is clearly documented at the appropriate levels within README.md and also developer.openactive.io

**Comment by lukehesluke** [comment]
action.yml:

```yml
name: 'OpenActive Test Suite'
description: 'Test suite for OpenActive implementations'
inputs:
  args:  # id of input
    description: 'Arguments to pass to `npm start` of OpenActive Test Suite'
    required: false
    default: ''
  config:  # id of input
    description: 'The path of a config file to copy into ./config/ of OpenActive Test Suite'
    required: false
    default: ''
  NODE_CONFIG:  # id of input
    description: 'JSON configuration string to pass into OpenActive Test Suite'
    required: true
    default: '{ "ci": true }'
  NODE_ENV:  # id of input
    description: 'Value of NODE_ENV environment variable to pass into OpenActive Test Suite'
    required: false
    default: ''
  NODE_APP_INSTANCE:  # id of input
    description: 'Value of NODE_APP_INSTANCE environment variable to pass into OpenActive Test Suite'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/openactive/test-suite:latest'
  args:
    - ${{ inputs.args }}
  env:
    FORCE_COLOR: 1
    NODE_CONFIG: ${{ inputs.NODE_CONFIG }}
    NODE_ENV: ${{ inputs.NODE_ENV }}
    NODE_APP_INSTANCE: ${{ inputs.NODE_APP_INSTANCE }}
```
