### ISSUE TITLE
Upgrade GitHub Actions ubuntu version (22 -> 24)

### ISSUE THREAD

**Issue by lukehesluke** [openactive/openactive-test-suite#697]
In this PR: https://github.com/openactive/openactive-test-suite/pull/696, I fixed ubuntu version from `ubuntu-latest` to `ubuntu-22.04`. This is because a change appears to have happened in Ubuntu which leads to this error:

![Screenshot 2024-10-15 at 13 27 56 (1)](https://github.com/user-attachments/assets/3d6ed8d5-2337-4a46-9606-c5e02596e038)

> Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

([link to the whole run](https://github.com/openactive/openactive-test-suite/actions/runs/11345965795/job/31554007370?pr=696))

Downgrading to 22.04 fixed this

## What's going on

This is what I have gathered so far:

* Adding this step to the `tests` job (in `.github/workflows/reference-implementation.yml`) before the `Install OpenActive.Server.NET dependencies` step may fix it as it will install an ICU package:
    ```yml
    # These are required for .NET globalization
    - name: Install ICU packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libicu-dev
    ```
